# Generated by Django 5.2.4 on 2025-08-19 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('district_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('thi_xa', 'Thị xã'), ('huyen', 'Huyện'), ('quan', 'Quận'), ('tp', 'Thành phố')], default='huyen', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('province_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('tinh', 'Tỉnh'), ('tp', 'Thành phố')], default='tinh', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CommuneOld',
            fields=[
                ('old_commune_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('xa', 'Xã'), ('phuong', 'Phường'), ('thi_tran', 'Thị trấn')], default='xa', max_length=50)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_communes', to='registry.district')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_communes', to='registry.province')),
            ],
        ),
        migrations.CreateModel(
            name='CommuneCurrent',
            fields=[
                ('commune_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('xa', 'Xã'), ('phuong', 'Phường'), ('thi_tran', 'Thị trấn')], default='xa', max_length=50)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='registry.district')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='registry.province')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='registry.province'),
        ),
        migrations.CreateModel(
            name='CommuneAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='registry.communecurrent')),
            ],
            options={
                'unique_together': {('commune', 'alias')},
            },
        ),
        migrations.CreateModel(
            name='Merger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('new_commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mergers', to='registry.communecurrent')),
                ('old_commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mergers', to='registry.communeold')),
            ],
            options={
                'unique_together': {('old_commune', 'new_commune')},
            },
        ),
    ]
