# Generated by Django 5.2.5 on 2025-08-19 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_alter_communeold_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communecurrent',
            name='district',
        ),
    ]
