# Generated by Django 5.2.5 on 2025-08-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_remove_communecurrent_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='type',
            field=models.CharField(choices=[('Thị xã', 'Thị xã'), ('Huyện', 'Huyện'), ('Quận', 'Quận'), ('Thành phố', 'Thành phố')], default='huyen', max_length=50),
        ),
        migrations.AlterField(
            model_name='province',
            name='type',
            field=models.CharField(choices=[('Tỉnh', 'Tỉnh'), ('Thành phốThành phố', 'Thành phố')], default='tinh', max_length=50),
        ),
    ]
