# Generated by Django 5.2.5 on 2025-08-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_alter_province_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='type',
            field=models.CharField(choices=[('Tỉnh', 'Tỉnh'), ('Thành phố', 'Thành phố')], default='Tỉnh', max_length=50),
        ),
    ]
