# Generated by Django 5.2.5 on 2025-08-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_alter_province_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communecurrent',
            name='type',
            field=models.CharField(choices=[('Xã', 'Xã'), ('Phường', 'Phường'), ('Thị trấn', 'Thị trấn')], default='Xã', max_length=50),
        ),
        migrations.AlterField(
            model_name='communeold',
            name='type',
            field=models.CharField(choices=[('Xã', 'Xã'), ('Phường', 'Phường'), ('Thị trấn', 'Thị trấn')], default='xa', max_length=50),
        ),
        migrations.AlterField(
            model_name='district',
            name='type',
            field=models.CharField(choices=[('Thị xã', 'Thị xã'), ('Huyện', 'Huyện'), ('Quận', 'Quận'), ('Thành phố', 'Thành phố')], default='Huyện', max_length=50),
        ),
        migrations.DeleteModel(
            name='CommuneAlias',
        ),
    ]
