# Generated by Django 5.2.5 on 2025-08-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_alter_communecurrent_type_alter_communeold_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communeold',
            name='type',
            field=models.CharField(choices=[('Xã', 'Xã'), ('Phường', 'Phường'), ('Thị trấn', 'Thị trấn')], default='Xã', max_length=50),
        ),
    ]
